name: Publish skymith-sdk to PyPI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/_publish_package.yaml"
      - ".github/workflows/publish-skymith-sdk.yaml"
      - "libs/skymith-sdk/**"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  publish-skymith-sdk:
    uses: ./.github/workflows/_publish_package.yaml
    with:
      working-directory: libs/skymith-sdk
    secrets: inherit
